### EJERCICIO 1

In [3]:
import pandas as pd

In [4]:
url = 'https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv?raw=true'
df = pd.read_csv(url, index_col=0)
df.head()

,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
iso_code,,,,,,,,,,,,,,,,,,,,,
AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
AFG,Asia,Afghanistan,2020-01-08,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
AFG,Asia,Afghanistan,2020-01-09,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

In [5]:

# 1. QuÃ© paÃ­ses se encuentran en el DataFrame
paises = df['location'].unique()
print(f"1. PaÃ­ses en el DataFrame:\n{paises}\n")

1. PaÃ­ses en el DataFrame:
['Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa' 'Andorra'
 'Angola' 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Asia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bonaire Sint Eustatius and Saba'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon'
 'Canada' 'Cape Verde' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Chile' 'China' 'Colombia' 'Comoros' 'Congo' 'Cook Islands' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czechia'
 'Democratic Republic of Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'England'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'Fiji' 'Finland'
 'France' 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia'
 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe'
 'Guam' 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'High income' 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Low income'
 'Lower middle income' 'Luxembourg' 'Macao' 'Madagascar' 'Malawi'
 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Martinique'
 'Mauritania' 'Mauritius' 'Mayotte' 'Mexico' 'Micronesia (country)'
 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Montserrat' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue'
 'North America' 'North Korea' 'North Macedonia' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Norway' 'Oceania' 'Oman'
 'Pakistan' 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay'
 'Peru' 'Philippines' 'Pitcairn' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar'
 'Reunion' 'Romania' 'Russia' 'Rwanda' 'Saint Barthelemy' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Scotland' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore'
 'Sint Maarten (Dutch part)' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'South Africa' 'South America' 'South Korea' 'South Sudan'
 'Spain' 'Sri Lanka' 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria'
 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor' 'Togo' 'Tokelau'
 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Upper middle income' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Vatican' 'Venezuela' 'Vietnam' 'Wales'
 'Wallis and Futuna' 'Western Sahara' 'World' 'Yemen' 'Zambia' 'Zimbabwe']

In [6]:
# 2. CuÃ¡ntos registros hay por continente
registros_por_continente = df['continent'].value_counts()
print(f"2. Registros por continente:\n{registros_por_continente}\n")

2. Registros por continente:
continent
Africa           91828
Europe           87498
Asia             80159
North America    66070
Oceania          38671
South America    22558
Name: count, dtype: int64

In [7]:
# 3. CuÃ¡ntos nuevos casos hubo como mÃ¡ximo en una fecha reportada por cada paÃ­s
max_nuevos_casos = df.groupby('location')['new_cases'].max()
print(f"3. MÃ¡ximos nuevos casos por paÃ­s:\n{max_nuevos_casos}\n")

3. MÃ¡ximos nuevos casos por paÃ­s:
location
Afghanistan          12314.0
Africa              316014.0
Albania              15405.0
Algeria              14774.0
American Samoa        1881.0
                     ...
Western Sahara           NaN
World             44236227.0
Yemen                  728.0
Zambia               26367.0
Zimbabwe             26671.0
Name: new_cases, Length: 255, dtype: float64

In [8]:
# 4. CuÃ¡l es el paÃ­s con el mayor GDP per cÃ¡pita (PBI)
pais_max_gdp_per_capita = df.loc[df['gdp_per_capita'].idxmax(), 'location']
max_gdp_per_capita = df['gdp_per_capita'].max()
print(f"4. PaÃ­s con mayor GDP per cÃ¡pita: {pais_max_gdp_per_capita} con {max_gdp_per_capita}\n")

4. PaÃ­s con mayor GDP per cÃ¡pita: iso_code
QAT    Qatar
QAT    Qatar
QAT    Qatar
QAT    Qatar
QAT    Qatar
       ...
QAT    Qatar
QAT    Qatar
QAT    Qatar
QAT    Qatar
QAT    Qatar
Name: location, Length: 1611, dtype: object con 116935.6

In [9]:
# 5. QuÃ© paÃ­s tiene la mayor cantidad de fumadoras femeninas
pais_max_fumadoras_femeninas = df.loc[df['female_smokers'].idxmax(), 'location']
max_fumadoras_femeninas = df['female_smokers'].max()
print(f"5. PaÃ­s con mayor cantidad de fumadoras femeninas: {pais_max_fumadoras_femeninas} con {max_fumadoras_femeninas}\n")

5. PaÃ­s con mayor cantidad de fumadoras femeninas: iso_code
MNE    Montenegro
MNE    Montenegro
MNE    Montenegro
MNE    Montenegro
MNE    Montenegro
          ...
MNE    Montenegro
MNE    Montenegro
MNE    Montenegro
MNE    Montenegro
MNE    Montenegro
Name: location, Length: 1611, dtype: object con 44.0

In [10]:
# 6. QuÃ© paÃ­s tiene la mayor cantidad de muertes por millÃ³n
pais_max_muertes_por_millon = df.loc[df['total_deaths_per_million'].idxmax(), 'location']
max_muertes_por_millon = df['total_deaths_per_million'].max()
print(f"6. PaÃ­s con mayor cantidad de muertes por millÃ³n: {pais_max_muertes_por_millon} con {max_muertes_por_millon}\n")

6. PaÃ­s con mayor cantidad de muertes por millÃ³n: iso_code
PER    Peru
PER    Peru
PER    Peru
PER    Peru
PER    Peru
       ...
PER    Peru
PER    Peru
PER    Peru
PER    Peru
PER    Peru
Name: location, Length: 1611, dtype: object con 6485.57

In [11]:
# 7. QuÃ© paÃ­s ha tomado las medidas mÃ¡s estrictas hasta ahora
pais_max_medidas_estrictas = df.loc[df['stringency_index'].idxmax(), 'location']
max_medidas_estrictas = df['stringency_index'].max()
print(f"7. PaÃ­s con medidas mÃ¡s estrictas: {pais_max_medidas_estrictas} con Ã­ndice {max_medidas_estrictas}\n")

7. PaÃ­s con medidas mÃ¡s estrictas: iso_code
ARG    Argentina
ARG    Argentina
ARG    Argentina
ARG    Argentina
ARG    Argentina
         ...
ARG    Argentina
ARG    Argentina
ARG    Argentina
ARG    Argentina
ARG    Argentina
Name: location, Length: 1615, dtype: object con Ã­ndice 100.0

In [14]:

# 8. CuÃ¡l fue el paÃ­s en alcanzar los 10,000 casos activos por primera vez
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df = df.dropna(subset=['date'])
df = df.sort_values(by='date')
df_paises_primeros_10000_casos_activos = df[df['total_cases'] >= 10000].groupby('location')['date'].min().sort_values()
pais_primeros_10000_casos_activos = df_paises_primeros_10000_casos_activos.idxmin()
fecha_primeros_10000_casos_activos = df_paises_primeros_10000_casos_activos.min()

In [15]:
print(f"8. PaÃ­s que alcanzÃ³ los 10,000 casos activos primero: {pais_primeros_10000_casos_activos} (alcanzado el {fecha_primeros_10000_casos_activos})\n")

8. PaÃ­s que alcanzÃ³ los 10,000 casos activos primero: Upper middle income (alcanzado el 2020-02-02 00:00:00)